# Generated by Django 3.1.4 on 2020-12-18 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=30)),
                ('question', models.TextField()),
                ('answer_1', models.CharField(max_length=50)),
                ('answer_2', models.CharField(max_length=50)),
                ('answer_3', models.CharField(max_length=50)),
                ('answer_4', models.CharField(max_length=50)),
                ('right_answer', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
